いいね機能の実装
e-kaneyuki/team_tenkue pull request #10
Opened 2020-12-29 14:20 UTC by Kotahiyo

## 概要
- Like モデルを作成
- １ユーザにつき１つのいいねしかできないようバリデーションを設定
- likes_controller を作成。未ログイン時にいいねボタンを押すとログイン画面に遷移するよう設定
- user モデルに投稿に対してすでにいいねしているかどうかを判定する already_liked メソッド作成
- 各 View の調整

### 以下画像
- ゲストユーザーで投稿にいいねした状態
<img width="1247" alt="スクリーンショット 2020-12-29 22 33 55" src="https://user-images.githubusercontent.com/69280992/103289947-c5f2b980-4a2b-11eb-8bee-8a57c32d2f96.png">

- ログアウトし、別ユーザーに変更した状態
<img width="1252" alt="スクリーンショット 2020-12-29 22 35 44" src="https://user-images.githubusercontent.com/69280992/103290077-09e5be80-4a2c-11eb-8313-b31e5c408f02.png">

- 別ユーザーでいいねした状態
<img width="1242" alt="スクリーンショット 2020-12-29 22 36 04" src="https://user-images.githubusercontent.com/69280992/103290112-1e29bb80-4a2c-11eb-95e8-6c8387dc08ad.png">

- 詳細画面
<img width="1240" alt="スクリーンショット 2020-12-29 22 36 36" src="https://user-images.githubusercontent.com/69280992/103290146-3699d600-4a2c-11eb-8a68-5f1a90b53613.png">

- ログインしていない状態でいいねを押下した画面
<img width="1246" alt="スクリーンショット 2020-12-29 22 37 08" src="https://user-images.githubusercontent.com/69280992/103290190-4b766980-4a2c-11eb-951b-5f373c46f275.png">

2020-12-30 01:31 UTC, masatoshisugita commented
特に問題なさそうです！LGTMです！

2020-12-30 09:23 UTC, yoshikazu-ishitsuka reviewed
コメントしましたので、ご確認をお願い致します。

2020-12-30 09:23 UTC, yoshikazu-ishitsuka commented on app/views/posts/index.html.erb
> +                        <span></span>
ここの\<span>は不要な気もしますが、どうでしょうか？

2020-12-30 09:23 UTC, yoshikazu-ishitsuka commented on app/views/posts/show.html.erb
> +                <span></span>
上と同じくここの\<span>も不要な気もしますが、どうでしょうか？

2020-12-30 09:23 UTC, yoshikazu-ishitsuka commented on db/migrate/20201221013347_create_likes.rb
> +      t.references :post, foreign_key: true
ここでbigint型の指定が無いのですが、下のschemaファイルを見ると正しくbigintになっているみたいです。
自分もここで初めて知ったのですが、referencesにすると自動でidがbigint型になるみたいです。
なので、一応大丈夫かとは思うのですが、他のマイグレーションファイルではbigintを指定していたので気になりました。
でも今回はこのままでも良いと自分は思います。

2020-12-30 10:14 UTC, Kotahiyo commented on db/migrate/20201221013347_create_likes.rb
> +      t.references :post, foreign_key: true
そうなんですね！私も初めて知りました！とりあえずこのままにしておきます！

2020-12-30 10:20 UTC, Kotahiyo commented on app/views/posts/index.html.erb
> +                        <span></span>
サンプルを見ると いいねがされていない（カウントが 0 の）場合、0 と表記されず何も表記されない状態になっていたため、このような実装にしています！

2020-12-30 10:20 UTC, Kotahiyo commented on app/views/posts/show.html.erb
> +                <span></span>
こちらも上記と同じ理由で設定しています！

2020-12-30 10:23 UTC, yoshikazu-ishitsuka commented
ありがとうございます！LGTMです！

2020-12-30 17:15 UTC, sew-sou19 requested changes
レビュー完了しました！
ご確認お願いします！
！

2020-12-30 17:15 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    if current_user
間違いではないですが、ここはdeviseのデフォルト機能を使えます。
`authenticate_user!`というヘルパーメソッドがあるので調べてみてください！

> 参考→https://github.com/heartcombo/devise#controller-filters-and-helpers

また、この処理を記述する際はDRY原則に気をつけてくださいー！

2020-12-30 17:15 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @like = Like.new
この記述は不要だと思いますー！
どこかで使用してますかね、、、？

2020-12-30 17:15 UTC, sew-sou19 commented on app/models/post.rb
> +  has_many :liked_users, through: :likes, source: :user
このリレーションを組んでる理由を知りたいです！

2020-12-30 17:15 UTC, sew-sou19 commented on db/migrate/20201221013347_create_likes.rb
> +      t.references :post, foreign_key: true
Rails5.2？から確か自動変換がされるようになったはずなのでこのままで大丈夫です。
詳しくは調べてみてくださいー！

2020-12-30 17:15 UTC, sew-sou19 commented on app/models/user.rb
> +  has_many :liked_posts, through: :likes, source: :post
ここもこのリレーションを組んでる理由を知りたいです！

2020-12-31 12:57 UTC, Kotahiyo commented on app/controllers/likes_controller.rb
> +    if current_user
device のデフォルト機能使用されていたのですね！
DRY 原則知りませんでした！これを機会に勉強します！
該当箇所修正いたしました！

2020-12-31 12:58 UTC, Kotahiyo commented on app/controllers/posts_controller.rb
> +    @like = Like.new
使用していませんでした！削除してます！

2020-12-31 13:00 UTC, Kotahiyo commented on app/models/post.rb
> +  has_many :liked_users, through: :likes, source: :user
記事に対して、どれだけのいいねがきているか分かるように組んでいたのですが、posts.likes.count で十分なので、liked_users の文は削除しております！

2020-12-31 13:07 UTC, Kotahiyo commented on app/models/user.rb
> +  has_many :liked_posts, through: :likes, source: :post
こちらも liked_posts は不必要だったので削除しています！
likes はユーザーが投稿に対していいねしているか判定するために組んでおります！

2020-12-31 13:09 UTC, Kotahiyo commented
修正いたしました！ご質問の回答に正確に答えられていないかもしれませんが、再度ご確認よろしくお願いします。

2020-12-31 17:35 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-31 17:35 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
他のコントローラーでも使用されてるので、application_controller.rbで`before_action`で設定してあげる方が綺麗ですが、このままでもひとまずは大丈夫です！

2021-01-01 10:40 UTC, Kotahiyo commented on app/controllers/likes_controller.rb
> +  before_action :authenticate_user!
なるほど！勉強になります！

2021-01-01 10:40 UTC, merged