Feature pr index
e-kaneyuki/team_tenkue pull request #2
Opened 2020-12-15 11:47 UTC by masatoshisugita

gitignoreに/vendor/bundleを追加して、チームで共有

2020-12-15 12:46 UTC, e-kaneyuki commented
gitignore でvender/bundleを追跡対象外にしたもの
PostsControllerのindexメソッドで一覧表示
postmodel　拝見しました。
私の勉強不足かもしれないので、ひとつ確認させてください。
indexメソッドについてですが、一覧表示する際に表示の順番って指定されていますか？
そこまでは必要ないですかね？

2020-12-15 12:52 UTC, masatoshisugita commented
指定していません。なので古い順から表示されるかと思います。
直したほうがよいですかね？？

2020-12-15 12:56 UTC, e-kaneyuki commented
いえ、意図されてたら問題ないかなと思ってます！
スルーパスっていうのも寂しいかなって😁

2020-12-15 13:07 UTC, yoshikazu-ishitsuka reviewed
コンフリクトの解消が必要に見えます。よろしくお願い致します。

2020-12-15 13:07 UTC, yoshikazu-ishitsuka commented on app/controllers/users/registrations_controller.rb
> +>>>>>>> 1941528... 掲示板一覧表示機能
この部分コンフリクトしてるように見えます！

2020-12-15 13:07 UTC, yoshikazu-ishitsuka commented on app/models/user.rb
> +>>>>>>> 1941528... 掲示板一覧表示機能
ここもコンフリクトしてるように見えます。

2020-12-15 13:18 UTC, masatoshisugita commented on app/models/user.rb
> +>>>>>>> 1941528... 掲示板一覧表示機能
確かにコンフリクトしてますね。。。
明日修正して再度プルリクします！

2020-12-16 00:07 UTC, masatoshisugita commented on app/models/user.rb
> +>>>>>>> 1941528... 掲示板一覧表示機能
コンフリクトの部分を修正しました。
またroutesと日本時間の設定(config/application.rb)が消えていたので修正しました。
![スクリーンショット 2020-12-14 11 38 55](https://user-images.githubusercontent.com/36495736/102287467-e0358d80-3f7d-11eb-84d0-a8d67cb7fb7b.png)
![スクリーンショット 2020-12-14 11 40 08](https://user-images.githubusercontent.com/36495736/102287479-e4fa4180-3f7d-11eb-894a-a9354cf9894d.png)

      一枚目が未ログイン状態、二枚目がゲストユーザでログインした状態です。

2020-12-16 01:56 UTC, Kotahiyo commented
拝見いたしました。素晴らしいと思うのですが一点だけ、
私もかねゆきさんと同じ意見なのですが、古い順から一覧表示されているのが気になりました。
サンプルを見る限り、新しい投稿から順に表示されているようなので、そのように変更した方が良いかと思いました。

order メソッド使ってもらえればすぐ実装可能かと思います。

その他は問題はないかと思います。

2020-12-16 02:20 UTC, yoshikazu-ishitsuka reviewed
コメント追記しましたので確認お願い致します。

2020-12-16 02:20 UTC, yoshikazu-ishitsuka commented on config/routes.rb
> +  get '/posts/index',to: 'posts#index'
この部分は`root`と`resources`を使用した方が良い気がします。

2020-12-16 02:55 UTC, masatoshisugita commented
rootとresourcesの設定をしました！

2020-12-16 03:24 UTC, yoshikazu-ishitsuka commented
修正ありがとうございます。
自分は現状問題無いと思いますのでLGTMです！

2020-12-16 04:36 UTC, e-kaneyuki commented
私も問題ないのかなと思います！

2020-12-16 09:03 UTC, sew-sou19 requested changes
ほぼ問題ないです！
細かい部分だけご確認お願いしますー！！
ご確認お願いしますー！！

2020-12-16 09:03 UTC, sew-sou19 commented on app/views/posts/index.html.erb
> +      <%# 未投稿の場合は「まだ投稿されたスレッドはありません。」と表示するように条件分岐すること %>
不要なコメントは削除しましょうー！

2020-12-16 09:03 UTC, sew-sou19 commented on app/views/posts/index.html.erb
> +              <% if current_user != nil && current_user.id == post.user_id %>
意味は同じですが、`current_user != nil`より「ユーザーがサインインしてるか」という意味の方がわかりやすいかなと思います！
```suggestion
              <% if user_signed_in? && current_user.id == post.user_id %>  
```

2020-12-16 09:25 UTC, sew-sou19 approved these changes
LGTMです！
です！

2020-12-16 09:42 UTC, merged