掲示板投稿機能を実装
e-kaneyuki/team_tenkue pull request #4
Opened 2020-12-18 15:22 UTC by Kotahiyo

## 概要
- new, create メソッドを作成
- Post model にバリデーションを実装
- view ファイルを作成
- エラーを表示する機能を実装
- 日本語化のため、rails-i18n という gem を導入
- config/locales/ja.yml を作成し、エラーメッセージをサンプル通りの文字列に変更

2020-12-19 08:04 UTC, masatoshisugita commented
・エラーメッセージファイルとnew.html.erbにbyebugが残っています！
・ルートのroot to: "posts#new"はいらないかと思います！

2020-12-19 08:05 UTC, masatoshisugita commented on app/views/layouts/_error_messages.html.erb
> +  <% byebug %>
ここのbyebugは不要かと思います！

2020-12-19 08:05 UTC, masatoshisugita commented on app/views/layouts/_error_messages.html.erb
> +        <% byebug %>
ここも同様です！

2020-12-19 08:05 UTC, masatoshisugita commented on app/views/posts/new.html.erb
> +      <% byebug %>
ここも同様です！

2020-12-19 08:05 UTC, masatoshisugita commented on config/routes.rb
> +  root to: "posts#new"
rootはposts/indexだと思うので削除したほうが良さそうですね

2020-12-19 20:04 UTC, Kotahiyo commented on app/views/layouts/_error_messages.html.erb
> +  <% byebug %>
該当箇所の修正いたしました。

2020-12-19 20:04 UTC, Kotahiyo commented on app/views/layouts/_error_messages.html.erb
> +        <% byebug %>
該当箇所の修正いたしました。

2020-12-19 20:05 UTC, Kotahiyo commented on app/views/posts/new.html.erb
> +      <% byebug %>
該当箇所の修正いたしました。

2020-12-19 20:05 UTC, Kotahiyo commented on config/routes.rb
> +  root to: "posts#new"
該当箇所の修正いたしました。

2020-12-19 22:20 UTC, masatoshisugita commented
確認しました！LGTMです！

2020-12-20 01:20 UTC, yoshikazu-ishitsuka reviewed
コメント致しましたので確認お願い致します。
あと可能なら投稿フォームとエラーメッセージの画像が欲しいです。

2020-12-20 01:20 UTC, yoshikazu-ishitsuka commented on app/views/layouts/_error_messages.html.erb
> +        <% object.errors.full_messages.each do |message| %>
ここのobject.errorsですが、調べるとmodel.errorsの方が一般的な気がしましたが、エラーメッセージは問題無く表示されていますでしょうか。
出来れば画像が欲しいです。

2020-12-20 01:20 UTC, yoshikazu-ishitsuka commented on app/views/posts/new.html.erb
> +<div class="post_wrapper">
こちらも出来れば投稿フォームの画像が欲しいです。

2020-12-20 01:20 UTC, yoshikazu-ishitsuka commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
`config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]`
ここの記述はどのような意味になりますでしょうか。

2020-12-20 01:20 UTC, yoshikazu-ishitsuka commented on config/locales/ja.yml
> +        content: 'TEXT'
転クエのサンプル表示だと「TEXT」でなくて「Text」みたいですね。
でも今回は直さなくてこのままでも良いと思います。

2020-12-20 10:50 UTC, Kotahiyo commented on app/views/layouts/_error_messages.html.erb
> +        <% object.errors.full_messages.each do |message| %>
![image](https://user-images.githubusercontent.com/69280992/102711355-5dedf600-42fc-11eb-9778-e335fc26bbd0.png)
![image](https://user-images.githubusercontent.com/69280992/102711360-71995c80-42fc-11eb-97fa-74013ff380cb.png)

model に変更して画像撮りました！

2020-12-20 10:52 UTC, Kotahiyo commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
すみません。参考サイトに記述されたのを引っ張ってきたので、日本語設定している locales 以下のファイルを読み込むために必要なのかと思ってました。
削除しても普通に動いたので、削除しています。

2020-12-20 10:53 UTC, Kotahiyo commented on config/locales/ja.yml
> +        content: 'TEXT'
ついでなので Text に変更しています！

2020-12-20 11:07 UTC, yoshikazu-ishitsuka commented
修正ありがとうございます！LGTMです！

2020-12-20 11:10 UTC, Kotahiyo commented
頂いたコメント箇所修正しました！
修正しました！

2020-12-20 13:14 UTC, sew-sou19 requested changes
ほぼOKです！
一箇所だけご確認お願いしますー！
ご確認お願いしますー！

2020-12-20 13:14 UTC, masato-sa93 commented on app/controllers/posts_controller.rb
> +      redirect_to controller: :posts, action: :index
```suggestion
      redirect_to root_path
```
でいい気がします！

2020-12-20 13:22 UTC, Kotahiyo commented on app/controllers/posts_controller.rb
> +      redirect_to controller: :posts, action: :index
ありがとうございます！修正いたしました！

2020-12-20 13:23 UTC, sew-sou19 approved these changes
LGTMです！

2020-12-20 13:47 UTC, merged