コメント投稿機能の実装
e-kaneyuki/team_tenkue pull request #6
Opened 2020-12-23 12:32 UTC by yoshikazu-ishitsuka

## 何か

- 投稿詳細ページでコメントができる
- コメントは140文字以内であること
- 投稿したコメントは、投稿詳細ページに一覧で表示される
- コメントの投稿内容が必須になっている（ブランクのまま投稿できないようになっている）
- バリデーションに反した際に、エラーメッセージが表示される
- 未ログイン時にはコメント投稿フォームが表示されないようになっている
- コメントの数がカウントされている
- N+1問題を発生させていない

## 変更ファイル
- .gitignore
- app/assets/stylesheets/templates/_posts.scss（自動フォーマット機能でインデントや;などが追記されただけです。）
- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- config/routes.rb
- app/views/templates/_header.html.erb
- app/views/posts/show.html.erb
- app/views/posts/index.html.erb
- app/models/user.rb
- app/models/post.rb
- app/models/comment.rb

----
## 参考画像

- ### コメント投稿機能
- ### コメント数表示機能

<a href="https://gyazo.com/69746d6ae58ce47a7f4b4540a1b64778"><img src="https://i.gyazo.com/69746d6ae58ce47a7f4b4540a1b64778.gif" alt="Image from Gyazo" width="642"/></a>

- ### エラーメッセージ表示
- ### ブランク不可と140文字制限

<a href="https://gyazo.com/80b1d56be34338e2d3288d86955ecf6c"><img src="https://i.gyazo.com/80b1d56be34338e2d3288d86955ecf6c.gif" alt="Image from Gyazo" width="608"/></a>

- ### 未ログイン状態だとコメント投稿フォームが表示されない

<a href="https://gyazo.com/fd141b47d1d7787f17eb08485b4b92a9"><img src="https://i.gyazo.com/fd141b47d1d7787f17eb08485b4b92a9.png" alt="Image from Gyazo" width="626"/></a>

- ### コメント一覧表示

<a href="https://gyazo.com/d307ac7b9a0dfd04915cc07d0d363724"><img src="https://i.gyazo.com/d307ac7b9a0dfd04915cc07d0d363724.png" alt="Image from Gyazo" width="688"/></a>

- ### N+1問題を発生させていない

- posts_controller.rb内に以下を記述
```
  def show
    @comment = Comment.new
    @comments = @post.comments.all.includes(:user).order(id: 'DESC')
    @comments_count = Comment.where(post_id: @post.id).count
  end

```

2020-12-23 12:49 UTC, masatoshisugita commented
確認しました！素晴らしいと思います！LGTMです！！

2020-12-23 19:43 UTC, Kotahiyo commented
確認しました！動画も撮ってあってとても見易かったです！LGTMです！

2020-12-24 14:31 UTC, sew-sou19 requested changes
レビュー完了しました！
ご確認と修正をお願いします！

2020-12-24 14:31 UTC, sew-sou19 commented on .gitignore
> +/db/migrate/20201213050412_create_posts.rb
不要なマイグレーションファイルなら削除しましょう！

2020-12-24 14:31 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +      redirect_to "/posts/#{@comment.post.id}"
`redirect to`のあとはプレフィックスかURLで遷移先を指定しましょう！

2020-12-24 14:31 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +      redirect_to "/posts/#{@comment.post.id}"
ここもです。

2020-12-24 14:31 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @comments_count = Comment.where(post_id: @post.id).count
あえてここでインスタンス変数としてコメント数を定義している意味って何かありますでしょうか？
もしなければ、viewファイルで記述している`post.comments.count`で十分かと思います。

基本的に、コントローラーの記述は少なくするのがベターです！

2020-12-24 23:52 UTC, yoshikazu-ishitsuka commented on .gitignore
> +/db/migrate/20201213050412_create_posts.rb
こちらのマイグレーションファイルなのですが、ぎぺーさんのpostsのマイグレーションファイルになってまして、自分のpostsマイグレーションファイルと二重になってしまいましたので削除したのですが、ぎぺーさんがこのプルリクエストをpullする時になにかエラーが出る可能性があると思いましたのでこちらに記述しました。
こちらは記述は不要ということでよろしいでしょうか。

2020-12-25 00:42 UTC, yoshikazu-ishitsuka commented on app/controllers/comments_controller.rb
> +      redirect_to "/posts/#{@comment.post.id}"
該当箇所の修正完了致しました。

2020-12-25 00:42 UTC, yoshikazu-ishitsuka commented on app/controllers/comments_controller.rb
> +      redirect_to "/posts/#{@comment.post.id}"
該当箇所の修正完了致しました。

2020-12-25 00:44 UTC, yoshikazu-ishitsuka commented on app/controllers/posts_controller.rb
> +    @comments_count = Comment.where(post_id: @post.id).count
すいません、特に意味なく定義していました。
こちらの削除とviewファイルへの追記完了致しました。

2020-12-25 00:47 UTC, sew-sou19 commented on .gitignore
> +/db/migrate/20201213050412_create_posts.rb
PULL時にはエラーは起きないと思います。
もしかしたらschima

2020-12-25 00:56 UTC, yoshikazu-ishitsuka commented on .gitignore
> +/db/migrate/20201213050412_create_posts.rb
該当箇所の削除修正完了致しました。

2020-12-25 00:57 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-25 01:22 UTC, merged