ゲストログイン機能
e-kaneyuki/team_tenkue pull request #7
Opened 2020-12-23 15:19 UTC by e-kaneyuki

ゲストログイン機能を作成しました。
以下の3点を実装したので確認をお願いします。
①ヘッダーに「ゲストログイン」のリンクを設置する
②ゲストユーザーとして、新規ユーザー登録を行わずにログインできる
③ゲストユーザーは、通常のユーザーと同じ機能を使用できる

2020-12-23 19:52 UTC, Kotahiyo reviewed
確認しました！いくつかコメントしたので確認お願いします！

2020-12-23 19:52 UTC, Kotahiyo commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
確か以前の壮さんからのレビューでこのファイルはいらないから削除して良いってコメントあった気がするので削除して良いと思います！

2020-12-23 19:52 UTC, Kotahiyo commented on config/routes.rb
> +    # delete 'logout'  => 'sessions#destroy'
このコメントアウトしてるのも不必要なら削除しちゃった方が良いと思います！

2020-12-23 19:52 UTC, Kotahiyo commented on app/views/templates/_header.html.erb
> +<%# ログインされている場合 %>
このコメントアウトしてるのも同様に削除しちゃった方が良いと思います！

2020-12-23 19:52 UTC, Kotahiyo commented on app/views/templates/_header.html.erb
> +<%# ログインされていない場合 %>
ここもですね！

2020-12-23 22:33 UTC, e-kaneyuki commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
確かにおっしゃってましたね。消します。

2020-12-23 22:36 UTC, e-kaneyuki commented on config/routes.rb
> +    # delete 'logout'  => 'sessions#destroy'
消しました

2020-12-23 22:37 UTC, e-kaneyuki commented on app/views/templates/_header.html.erb
> +<%# ログインされている場合 %>
未対応→次はここから(覚え書き)

2020-12-24 00:27 UTC, masatoshisugita reviewed
1点だけコメントしました！確認お願いします！

2020-12-24 00:27 UTC, masatoshisugita commented on app/views/layouts/application.html.erb
>        <%= yield %>
ここのyieldはいらないかと思います！(yieldが2つあるため)

2020-12-24 00:48 UTC, yoshikazu-ishitsuka reviewed
コメントしましたので、ご確認お願い致します。

2020-12-24 00:48 UTC, yoshikazu-ishitsuka commented on Gemfile.lock
> +  x86_64-darwin-19
これはなにかgemをインストールされたのでしょうか。

2020-12-24 00:48 UTC, yoshikazu-ishitsuka commented on Gemfile.lock
> +   2.2.2
ここでbundlerのバージョンが変わっちゃってますね。
一応新しいバージョンだから大丈夫かとは思いますが。もし直せるなら直した方が良いのかもしれませんね。

2020-12-24 00:48 UTC, yoshikazu-ishitsuka commented on app/assets/stylesheets/modules/_body.scss
>  .body {
こちら大幅に編集されているようですが、基本scssファイルの中身は編集しないで良いと思いますがこちらはどのような編集をされたのでしょうか。

2020-12-24 00:48 UTC, yoshikazu-ishitsuka commented on app/views/layouts/application.html.erb
> +</div>
不要な空白は消した方が良い気がしますね。

2020-12-24 03:49 UTC, e-kaneyuki commented on app/views/layouts/application.html.erb
>        <%= yield %>
なるほど！消します！(未対応　覚え書き)

2020-12-24 03:50 UTC, e-kaneyuki commented on Gemfile.lock
> +  x86_64-darwin-19
あら？そんな認識はありませんでしたが、
不要だと思いますので削除を前提に確認します。

2020-12-24 03:52 UTC, e-kaneyuki commented on Gemfile.lock
> +   2.2.2
OKです。修正できそうなら直してみます！(未対応 覚え書き)

2020-12-24 04:07 UTC, e-kaneyuki commented on app/assets/stylesheets/modules/_body.scss
>  .body {
確かに大幅編集されていますね。何か編集当初は何か意図して編集したのかと思うのですが、commitしておらず編集理由がわかりませんでした。先ほど元々のコードに書き換えましたが表示には全く影響はありませんでしたので、以前からのものへ戻しました。
ご指摘ありがとうございます。

2020-12-24 04:12 UTC, e-kaneyuki commented on app/views/layouts/application.html.erb
> +</div>
ありがとうございます。(未対応　覚え書き)

2020-12-24 04:17 UTC, e-kaneyuki commented on app/views/templates/_header.html.erb
> +<%# ログインされていない場合 %>
済

2020-12-26 11:47 UTC, yoshikazu-ishitsuka commented
ありがとうございます。LGTMです！

2020-12-26 12:05 UTC, masatoshisugita commented
確認しました！LGTMです！！

2020-12-26 14:59 UTC, sew-sou19 requested changes
レビュー完了しましたー！
ご確認＆修正をお願いいたします！

2020-12-26 14:59 UTC, sew-sou19 commented on app/views/templates/_header.html.erb
> +         <%= link_to 'ログアウト', users_guest_logout_path, method: :delete %>
ここって、ゲストユーザ以外の時もログアウトできるようになってますでしょうか？
もしなっていれば大丈夫です！
！

2020-12-26 14:59 UTC, sew-sou19 commented on config/routes.rb
> +  root to: "posts#index"
rootパスが重複してるので削除しましょう！
また、`resources :post`も重複してます。ルーティングは重要なので必ず確認しましょうー！

2020-12-26 14:59 UTC, sew-sou19 commented on config/routes.rb
> +    delete 'users/guest_logout', to: 'users/sessions#destroy'
これはおそらく不要ですね！

2020-12-26 15:11 UTC, e-kaneyuki commented on app/views/templates/_header.html.erb
> +         <%= link_to 'ログアウト', users_guest_logout_path, method: :delete %>
ゲストログインのみ対応できるようにしていました。
修正致しします。
ありがとうございます。

2020-12-26 15:11 UTC, e-kaneyuki commented on config/routes.rb
> +  root to: "posts#index"
ありがとうございます。削除しました。

2020-12-26 15:13 UTC, e-kaneyuki commented on config/routes.rb
> +    delete 'users/guest_logout', to: 'users/sessions#destroy'
ゲストユーザーのみログアウトできるような実装だったのでこのルーティングを作ったのだと思います。
前述のログアウト機能と同様修正いたします。

2020-12-27 02:44 UTC, yoshikazu-ishitsuka reviewed
再度確認致しました。コメントの確認おねがいします。

2020-12-27 02:44 UTC, yoshikazu-ishitsuka commented on app/views/templates/_header.html.erb
>        </li>
ここの（閲覧用）の記述なのですが、ゲストユーザーは閲覧と投稿も出来るので特に必要無い気もしますね。

2020-12-27 02:58 UTC, e-kaneyuki commented on app/views/templates/_header.html.erb
>        </li>
確かにそうですね。
対応しました！ありがとうございます。

2020-12-27 03:00 UTC, yoshikazu-ishitsuka commented
LGTMです！

2020-12-27 05:58 UTC, sew-sou19 requested changes
もう少しだけお付き合いください🙇‍♂️

2020-12-27 05:58 UTC, sew-sou19 commented on app/views/templates/_header.html.erb
> +         <%= link_to 'ログアウト', users_sign_out_path, method: :get %>
ここはdeviseのデフォルトのパスが用意されているので、そちらを使用した方がいいですね！
```suggestion
         <%= link_to 'ログアウト', destroy_user_session_path, method: :get %>
```

2020-12-27 05:58 UTC, sew-sou19 commented on config/routes.rb
> +    get '/users/sign_out', to: 'users/sessions#destroy'
わざわざ定義しなくても、deviseのデフォルトのパスがあるはずですー！
コンソールで`rails routes`をすると、現状使えるパスが一覧表示されるので、そちらを確認してみましょう！

2020-12-27 17:13 UTC, e-kaneyuki commented on app/views/templates/_header.html.erb
> +         <%= link_to 'ログアウト', users_sign_out_path, method: :get %>
ありがとうございます。！deviseの機能にルーティングが備わっていたんですね。
アドバイス頂けたのでREADMEとbundle exec rails routesを確認したところ確かに記載されていました。
私の解釈が間違っていなければ今回の修正で問題ないかなと思っています。

2020-12-27 17:13 UTC, e-kaneyuki commented on config/routes.rb
> +    get '/users/sign_out', to: 'users/sessions#destroy'
こちらについても修正対応いたしました。

2020-12-28 03:22 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-28 03:30 UTC, merged