正規表現とバリデーション
e-kaneyuki/team_tenkue pull request #8
Opened 2020-12-26 01:15 UTC by masatoshisugita

【正規表現とバリデーション】

・Userモデル
メールアドレスに全角文字が含まれていないこと
パスワードは8文字以上32文字以下であること
パスワードは半角英字と半角数字のいずれとも含まれていること

・Postモデル
投稿内容がnot null
投稿内容は140文字以内

・Commentモデル
コメント内容がnot null
コメント内容は140文字以内

【やったこと】
上記3つのmodel単体のrspecとバリデーションを実装

以下は
```
bundle exec rspec
```
を実行した後の結果です
![](https://i.gyazo.com/040da6c266a00d410fa5db4afbe5f063.png)

確認の方、よろしくお願いします！

2020-12-26 04:07 UTC, yoshikazu-ishitsuka reviewed
コメントしましたのでご確認お願い致します。

あとテストの部分なのですが、Factorybot.buildの箇所を繰り返し書いているのが大変そうに見受けられました。自分はテストの時は一番上にbefore doでFactorybotを先に記述するやり方でやっていますので、ご参考になればと思います。
今回はぎぺーさんのやり方で特に問題は無いと思います。

2020-12-26 04:07 UTC, yoshikazu-ishitsuka commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
emailは全角文字が含まれていないことが条件だと思いますが、これだと全角が入っていませんでしょうか？

2020-12-26 04:07 UTC, yoshikazu-ishitsuka commented on spec/factories/users.rb
> +    sequence(:email) { |n| "test#{n}@example.com" }
ここのemailにシーケンスを使われているようですが、今回はemailには特に一意性制約は使われていないと思いますので、こちらのシーケンスはいらないような気もしますがどうでしょうか？

2020-12-26 04:07 UTC, yoshikazu-ishitsuka commented on spec/factories/users.rb
> +    sequence(:id, &:to_s)
こちら勉強のために教えて頂きたいのですが、sequence(:id, &:to_s)はuser_idをstring型に変えているのでしょうか？もしそうならなぜstring型に変えているのかご教授頂きたいです。

2020-12-26 05:51 UTC, masatoshisugita commented on spec/factories/users.rb
> +    sequence(:id, &:to_s)
確かにおかしいですね（笑）
to_iにしようかと思いましたがid自体消しても生成されるため、問題無かったのでその部分は削除しました！

2020-12-26 05:52 UTC, masatoshisugita commented on spec/factories/users.rb
> +    sequence(:email) { |n| "test#{n}@example.com" }
そうですね！ただ基本的にメールアドレスはユニークだと思うので今回はそのままにします！

2020-12-26 05:57 UTC, masatoshisugita commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
こちら確認したところ、全角文字は入っていないと思います！

2020-12-26 12:29 UTC, yoshikazu-ishitsuka commented on spec/models/post_spec.rb
> +    it "contetnが空なら無効なこと" do
すいません、細かい所なのですがこちらの「content」がタイポされているようです。

2020-12-28 04:31 UTC, sew-sou19 requested changes
レビュー完了しました！
ご確認＆修正をお願いします！

2020-12-28 04:31 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +    it "commentが有効なこと" do
細かいですが、日本語でやるなら「有効なこと」より「登録できること」の方がわかりやすいかと思いますー！

2020-12-28 04:31 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +    end
文字数でのバリデーションを行っている場合は、閾値でOKとNGの両方をテストするようにしましょう！
今回で言えば「140文字以内なら登録できること」のテストがあるとより親切です！

2020-12-28 04:31 UTC, sew-sou19 commented on spec/models/post_spec.rb
> +  describe "有効な値の時" do
commentモデルと同じですー！

2020-12-28 04:31 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +  describe "有効な値の時" do
ここもcommentモデルと同じですー！

2020-12-28 04:58 UTC, masatoshisugita commented on spec/models/comment_spec.rb
> +    it "commentが有効なこと" do
修正します！

2020-12-28 04:58 UTC, masatoshisugita commented on spec/models/comment_spec.rb
> +    end
確かにそうですね！修正します！

2020-12-28 05:19 UTC, masatoshisugita commented
修正しました！確認よろしくお願いします！

2020-12-28 06:37 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-28 06:39 UTC, merged